### ISSUE TITLE
Expose data

### ISSUE THREAD

**Issue by mykiimike** [icubam/icubam#170]
Hi there,

I would like to say good job you guys on the project. My question is do you plan to expose consolidated data to the public ?

Thanks
Michael

**Comment by fambon** [comment]
@olivierteboul  => I advertized the project in https://opencovid19.fr/

posted github url on their slacks in channel #shared-hospital-bed-availability

![image](https://user-images.githubusercontent.com/6331006/78546196-4bc73880-77fd-11ea-8dce-384561ea7d88.png)

**Comment by dulacarnold** [comment]
Hi Mykiimike, we are currently providing the data to local agencies, the decision to publish it in any form is beyond our control.
