### ISSUE TITLE
Use werkzeug.secure_filename instead of clean_path?

### ISSUE THREAD

**Issue by rprimet** [icubam/icubam#216]
https://github.com/icubam/icubam/blob/71fcceea76a465e44289c84f7b9d9be038e39621/icubam/www/handlers/upload_csv.py#L9

Would it be better to use `werkzeug.safe_file_name` (either by importing it or by copying the source -- it seems self-contained) rather than rolling our own sanitisation code ?

**Comment by dulacarnold** [comment]
Yes, agree that roll-your-own is not a good idea (although I'm /pretty/ confident).  I didn't want to include all of werkzeug just for the sanitation code but license-permitting we can copy/paste it.  Will look at this.

**Comment by dulacarnold** [comment]
I had a look at `secure_file_name` and I'm pretty confident we're doing a superset of their cleaning.  In the end we only allow alphanumeric characters into the string anyways, anything happening before is mainly to avoid butchering anything unintentionally weird.

**Comment by dulacarnold** [comment]
Even better I've outright removed using the filename.
