### ISSUE TITLE
RefererNotAllowedMapError when testing map on qualification docker server

### ISSUE THREAD

**Issue by VincentRouvreau** [icubam/icubam#227]
The google map appears and then disappear on backoffice qualification server (not tested, but maybe on developper version too).
Google Maps JavaScript API error: [RefererNotAllowedMapError](https://developers.google.com/maps/documentation/javascript/error-messages#referer-not-allowed-map-error) Your site URL to be authorized

**Comment by pgraverdy** [comment]
Yes. The issue with the google api used on qualif is that the domain of the website is not associated/valid for this api key, so the map is just briefly xhown, then raises an issue.

The domain for the server is the hostname of the Inria VM. When we move to docker in prod and qualif, then we can jsut use the key for qualif (and do the redirect for the qlf domain name to the IP address of the VM.

**Comment by dulacarnold** [comment]
Yes, you need to set your own API key for non icubam.net domains.
