### ISSUE TITLE
Add the equivalent of /version to the back-office

### ISSUE THREAD

**Issue by rprimet** [icubam/icubam#228]
It would be nice to have a way of performing a quick health check on the backoffice too, similar to the `/version` route on the "main" server.

**Comment by rth** [comment]
I think we should be able to re-use the same handler under `icubam/www/handlers/version.py` folder and registed it routes in `icubam/backoffice/server.py`.

**Comment by maximedenes** [comment]
Reusing the same handler is not completely straightforward, since handlers in the two servers use different initialization data, IIUC. I'll look into it more tomorrow.

**Comment by rth** [comment]
@rprimet is this still relevant? The backoffice  now has a /health endpoint. Should we close it?

**Comment by rprimet** [comment]
Yep I think we should close it then, thanks!
