### ISSUE TITLE
Update dev_install.md

### ISSUE THREAD

**Issue by dulacarnold** [icubam/icubam#23]
We should update the dev_install instructions, and might as well merge into the README.md

**Comment by rth** [comment]
As of today the `dev_install.md` are actually fairly accurate (just went through them). 

Also it doesn't hurt to have a separate file, as it's mostly non relevant information for most people arriving at the repo. Maybe adding a `Contributing` section with a link `dev_install.md` could be enough?

**Comment by rth** [comment]
Closing as resolved.
