### ISSUE TITLE
Squash PRs by default

### ISSUE THREAD

**Issue by rth** [icubam/icubam#241]
I would propose to squash PRs by default, so that they correspond to 1 commit on master (it's a Github option under settings). This would make it easier to,
 - revert changes if needed on master
 - cherry-pick commits between branches
 - generally follow what's going on in master. Right now we don't really rewrite commit history in PRs and it's a bit messy on master with lots of commits for fixing linter etc.

Thoughts?

**Comment by maximedenes** [comment]
This is just some experience feedback from larger collaborative projects, feel free to ignore it if it does not seem relevant to ICUBAM.

The general idea is usually to make commits that have independent meaning. A PR should be just one change, small or large (new feature, bug fix, improvement,...). For small changes, it usually means one commit, indeed. For large ones, though, it often makes sense to keep a series of commits.

Having a broken commit followed by a fix in another commit is indeed often painful for bisecting or cherry-picking, so in these cases it is often better to squash these two commits. Enforcing that all PRs contain only one commit seems a bit rigid, as requiring PRs to have a reasonably clean history is often enough for the purposes written above.

**Comment by rth** [comment]
> Having a broken commit followed by a fix in another commit is indeed often painful for bisecting or cherry-picking, so in these cases it is often better to squash these two commits. Enforcing that all PRs contain only one commit seems a bit rigid, as requiring PRs to have a reasonably clean history is often enough for the purposes written above.

I'm not saying we should not allow current behavior for exceptionally long PRs with clean history, where each commit passes CI. That's far from being the case for current PRs though. 

If you look at master, you'll see that most of those commits are about yapf or syncing branch with master then re-applyng yapf / fixing tests ^^. Personally I find it easier to merge master into a PR to sync, than rebasing particularly with multiple commits in the diff -- there are just fewer merge conflicts to fix. That's also what Github proposes in the UI. Asking contributors to rewrite commits in PR to clean history is doable, but a bit more tedious. So that's why I think the default should be squashing, optionally with an option to merge for contributors who know what they are doing and are comfortable rewriting commit history.

Just looking for an improvement with minimal effort.

**Comment by dulacarnold** [comment]
I'm not against it, how do people disable the default if they want to keep the commit history?

**Comment by maximedenes** [comment]
> I think the default should be squashing, with an option to merge for contributors who know what they are doing and are comfortable rewriting commit history

Sounds very reasonable.

> I'm not against it, how do people disable the default if they want to keep the commit history?

The developer handling the PR can click on the arrow on the right of the merge button and select the precise merge action (rebase, squash, or merge commit).

**Comment by dulacarnold** [comment]
So it's not clear how to change the actual default, but I disabled the full merge for (default is squash).  Not sure about the rebase option.
