### ISSUE TITLE
backoffice (v0.3.0): /list_tokens HTTP 500 internal server error

### ISSUE THREAD

**Issue by pgraverdy** [icubam/icubam#251]
Getting a HTTP 500 internal server error on /list_tokens in backoffice with fake DB data.

- on master v0.3.0 (31fffff)
- generated the fake db before launching the Docker container.
- launched in dev mode locally using `docker-compose -f docker/docker-compose-core.yml --project-directory .  up
`
- URL http://localhost:8890/bo/ then http://localhost:8890/bo/list_tokens

```
icubam-bo-server  | HTTPServerRequest(protocol='http', host='localhost:8890', method='GET', uri='/bo/list_tokens', version='HTTP/1.1', remote_ip='172.24.0.1')
icubam-bo-server  | Traceback (most recent call last):
icubam-bo-server  |   File "/root/miniconda3/envs/icubam/lib/python3.8/site-packages/tornado/web.py", line 1697, in _execute
icubam-bo-server  |     result = method(*self.path_args, **self.path_kwargs)
icubam-bo-server  |   File "/root/miniconda3/envs/icubam/lib/python3.8/site-packages/tornado/web.py", line 3174, in wrapper
icubam-bo-server  |     return method(self, *args, **kwargs)
icubam-bo-server  |   File "/home/icubam/icubam/backoffice/handlers/tokens.py", line 46, in get
icubam-bo-server  |     self.render_list(
icubam-bo-server  |   File "/home/icubam/icubam/backoffice/handlers/base.py", line 38, in render_list
icubam-bo-server  |     columns = json.dumps([x['key'] for x in data[0]])
icubam-bo-server  | IndexError: list index out of range
```

**Comment by maximedenes** [comment]
This seems to be because https://github.com/icubam/icubam/commit/fd464da6504be58302fa8d6132802088bacac807 assumes data sent to `render_list` tot be non-empty.

**Comment by rth** [comment]
We should understand why this hasn't been cough by https://github.com/icubam/icubam/blob/31fffff786e46be08d61051618607d991d744b40/icubam/backoffice/server_test.py#L57 Unless there are tokens in the test DB by default.

If we are not testing this configuration, then fine (and we should add it). But my suspicion is that `test_homepage_without` expected to tests all handlers is actually not working as expected.  https://github.com/icubam/icubam/issues/197

**Comment by maximedenes** [comment]
Thanks for the pointers, I'll investigate the issues with testing now.
