### ISSUE TITLE
use url shortener techniques to authenticated via hash instead of jwt

### ISSUE THREAD

**Issue by olivierteboul** [icubam/icubam#280]
jwt as long. We could have the same amount of security with only a hash, that we could keep in the database hash-->(user, icu). This way we can better control url length.

**Comment by rth** [comment]
What's the maximum URL length we need? Right now it's around 100 characters, right? Not too familiar with JWT spec, but as far as I can see the prefix is the same for different input for a given secret (seems to be the JWT header),
```
    cfg = config.Config('resources/test.toml')
    tkn = token.TokenEncoder(cfg)

    for userid in [2, 3, 4, 1234]:
        encoded = tkn.encode(userid)
        print(userid, encoded)
```
produces
```
2       eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6Mn0.doSn9H8sl528CyQZWGM8L1JjiXSVmd87xGUJ4tU7qdQ
3       eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6M30.8XFLkYbDyUkkeSB-meGGdoftNfbdA-aGEU4TnJQgwaY
4       eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6NH0.DrSGRgAubFQvmPYc4V2PiK8mu_bbLTMJr1VvL3cCwEo
1234    eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MTIzNH0.yygWv0coksmbkOzciNVuJi28_WN-9IeBmxaVS4kdBRY
invalid eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImludmFsaWQifQ.KWQhiOMsgodU7AN1XV7RjhoI7zlnvfLyBSY3o8wu5Yg
```

can't we drop the first prefix, and recompute it from any userid on the server -- that's 36 characters less? It doesn't seem to be timestampted.  Do you see a similar pattern in other tokens? Somewhat hacky I agree.

**Comment by rth** [comment]
Following discussion with @dulacarnold the issue was mostly solved in https://github.com/icubam/icubam/pull/266, so this issue is a nice to have but not critical improvement.

**Comment by rth** [comment]
Closing as resolved in https://github.com/icubam/icubam/pull/378
