### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'DotMap' and 'int'

### ISSUE THREAD

**Issue by rth** [icubam/icubam#327]
Right now when a config value is missing, it returns a DotMap object. And then errors like 
```
TypeError: unsupported operand type(s) for *: 'DotMap' and 'int'
```
It would be nice to return None by default to make these errors a bit more explicit, and error handling nicer.

I though @dulacarnold mentioned that this was done, but we saw this again during last deployment.

**Comment by olivierteboul** [comment]
It is still one. Thinking about a way to solve it...

**Comment by rth** [comment]
After investigation I don't think we can do anything about it on our side. The problem is that when one does `config.db.non_exitsting_value`, `config.db` is a `DotMap` value and then apparently `DotMap(..).db` returns an empty `DotMap` object. So it's completely up to the dotmap library how to handle that.

**Comment by rth** [comment]
Closing as I don't think we can do much about it.

A possible workaround currently is to check that the key exists e.g. `config.server.has_key(key)` before using it.
