### ISSUE TITLE
Make API auth errors more consistent.

### ISSUE THREAD

**Issue by dulacarnold** [icubam/icubam#337]
Currently an API GET by a UPLOAD key returns a 503, but an API GET by a MAP key redirects to /error, with the standard no-auth error for /index, which is misleading.

**Comment by maximedenes** [comment]
Returning a 503 without a redirection seems better for an API call. Errors are easier to detect, etc. For user facing URLs, a redirection is nicer, of course. So I'd rather fix this issue by issuing 503 for all API auth errors.

**Comment by dulacarnold** [comment]
Agreed, that's what I had in mind as well. I'm just not entirely sure where the redirect is happening in the code... :)

**Comment by olivierteboul** [comment]
it happens in www/server.py line 67.
What happens is: the `@tornado.web.authenticated` decorator calls `self.get_current_user`, if it returns None, it redirects to the `login_url` as defined in the construction of the `tornado.web.Application`. If you wish to return an http error, i believe a good way to do so is to `self.set_status(503)` inside the `get_current_user()`.

**Comment by olivierteboul** [comment]
not sure the solution works. but the diagnosis is correct i believe.

**Comment by olivierteboul** [comment]
#338 should solve the issue

**Comment by olivierteboul** [comment]
#342 definitely solves it
