### ISSUE TITLE
Deprecate HDF5 export

### ISSUE THREAD

**Issue by rth** [icubam/icubam#348]
I propose to deprecate HDF5 export in /db/ endpoints,

https://github.com/icubam/icubam/blob/6f039d3e9bc274a7842f20b6181a4ed611f91c98/icubam/www/handlers/db.py#L109

Currently this will fail anyway because pytables is not in the list of dependencies.

For binary representation of columnar data, I would propose Appache parquet instead (pd.DataFrame.to_parquet) which would need to add `pyarrow`.

The advantage is that it should make a bit easier to read those files from other languages e.g. R (using the R arrow backend).

**Comment by tgy** [comment]
Clearly, let's just drop it. This was my idea at the beginning but CSV is much more general.

Good point.
